AllCops:
  Exclude:
    - db/schema.rb
    - config/puma.rb
    - bin/*
  TargetRubyVersion: 2.3
LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 10
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
