language: ruby

rvm:
  - 2.3.1

sudo: required
env:
  - RAILS_ENV=test SH=bash
  global:
    - PGPORT=5433
    - PGHOST=localhost
    - DATABASE_URL=postgres://localhost:5433/test201607082330_test
services:
  - postgresql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'CREATE DATABASE test201607082330_test;'