parser_settings:
  - host: 'http://www.gsmarena.com/'
    host_check_stamp_regexp: 'GSMArena\.com'
    brand_page_link_regexp: '<a[^<]+?-\d+\.php\">[^<]+?<\/a>'
    brand_other_page_link_regexp: '<a[^<]+-p\d+\.php\">\d+<\/a>'
    brand_parse_link_name_regexp: '>([^<]+)<'
    brand_parse_link_href_regexp: 'href=\"([^\"]+)\"'
    brand_page_check_stamp_regexp: 'review-body'
    model_page_link_regexp: '<a href=\"[^<]+\.php\">.+?<\/a>'
    model_link_regexp: '<li>[^<]*?(<a href[^>]+\.php">.+?img.+?)<\/li>'
    model_parse_link_href_regexp: 'href=\"([^\"]+)\"'
    model_parse_link_img_src_regexp: 'src=\"?([^ ]+)\"? '
    model_parse_link_name_regexp: '>([^<]+)<'
    model_parse_link_title_regexp: 'title=\"?([^\"]+)\"? '
