# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1496c747bb55b7f10119a101af37e6b21f17489e7c725190bb2d9fe763e8b009ce27ae75e10a12fcde808acf57d45b28f976817b1a1a23316e00329f85a19c77

test:
  secret_key_base: 3212c7288e34eb1d321e5eac1d658f8c5592d90096ac67d8ed78328f530c95d12357fa6ca389f2ace6ae469680769858536133748893faf79aa88d45e2d79ecb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
